// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcgegagtdjqkmfcishcr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jZ2VnYWd0ZGpxa21mY2lzaGNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NTU5OTgsImV4cCI6MjA3MDIzMTk5OH0.5z6xUwCJ3d9Jun5449WYb4lQ1TJyqj71vFeJUN0bs24";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});